services:

  mysql:
    image: mysql:8.0
    container_name: openmetadata_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: openmetadata_root
      MYSQL_DATABASE: openmetadata_db
      MYSQL_USER: openmetadata_user
      MYSQL_PASSWORD: openmetadata_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  execute-migrate-all:
    image: openmetadata/server:1.3.1
    container_name: execute_migrate_all
    command: "./bootstrap/openmetadata-ops.sh migrate"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: openmetadata_user
      DB_PASSWORD: openmetadata_password
      DB_PARAMS: allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      OM_DATABASE: openmetadata_db
    depends_on:
      mysql:
        condition: service_healthy
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: openmetadata_elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  openmetadata-server:
    image: openmetadata/server:1.3.1
    container_name: openmetadata_server
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      execute-migrate-all:
        condition: service_completed_successfully
    environment:
      OPENMETADATA_SERVER_HOST: 0.0.0.0

      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: openmetadata_user
      DB_PASSWORD: openmetadata_password
      DB_PARAMS: allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      OM_DATABASE: openmetadata_db

      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200

      PIPELINE_SERVICE_CLIENT_ENDPOINT: http://ingestion:8080
      PIPELINE_SERVICE_CLIENT_VERIFY_SSL: no-ssl
      PIPELINE_SERVICE_CLIENT_CLASS_NAME: org.openmetadata.service.clients.pipeline.airflow.AirflowRESTClient
      SERVER_HOST_API_URL: http://openmetadata-server:8585/api
      AIRFLOW_USERNAME: admin
      AIRFLOW_PASSWORD: admin

    ports:
      - "8585:8585"

  ingestion:
    image: openmetadata/ingestion:1.3.1
    container_name: openmetadata_ingestion
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      openmetadata-server:
        condition: service_started
    entrypoint: /bin/bash
    command: "/opt/airflow/ingestion_dependency.sh"
    environment:
      OPENMETADATA_HOST: http://openmetadata-server:8585/api
      OPENMETADATA_SERVER_URL: http://openmetadata-server:8585/api
      OPENMETADATA_SERVER_HOST: openmetadata-server
      OPENMETADATA_SERVER_PORT: 8585
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dag_generated_configs
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__WEB_SERVER_HOST: 0.0.0.0
      AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: "/opt/airflow/dag_generated_configs"
      DB_HOST: mysql
      DB_PORT: 3306
      AIRFLOW_DB: openmetadata_db
      DB_USER: openmetadata_user
      DB_PASSWORD: openmetadata_password
      AIRFLOW_DB_HOST: mysql
      AIRFLOW_DB_PORT: 3306
    ports:
      - "8080:8080"
    volumes:
      - ingestion-volume-dag-airflow:/opt/airflow/dag_generated_configs
      - ingestion-volume-tmp:/tmp

volumes:
  mysql_data:
  es_data:
  ingestion-volume-dag-airflow:
  ingestion-volume-tmp: